import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Reel",
  description: "Generated by create next app",
};

export default function ProfileLayout({ children }: { children: React.ReactNode }) {
  return <div>{children}</div>;
}
