import type { Metadata } from "next";
import MainProfile from "./components/MainProfile";

export const metadata: Metadata = {
  title: "Profile",
  description: "Generated by create next app",
};

export default function ProfileLayout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <MainProfile />
      {children}
    </div>
  );
}
