import type { Metadata } from "next";
import ExploreSearch from "./components/ExploreSearch";

export const metadata: Metadata = {
  title: "explore",
  description: "Generated by create next app",
};

export default function ProfileLayout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <ExploreSearch />
      {children}
    </div>
  );
}
